name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    environment: Docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: sonjoybarman/leaning-ci-cd

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Action completed
        run: echo "Docker image published successfully!"
