name: First Demo Action

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo add other actions to build,
          echo test, and deploy your project

      - name: List files
        run: ls -la

      - name: Display current directory
        run: ls $GITHUB_WORKSPACE

      - name: Print GitHub context
        env:
          GITHUB_WORKSPACE: ${{ toJson(github) }}
        run: echo "GitHub context"

      - name: Action completed
        run: echo "Action completed successfully!"
